### PR TITLE
fixes #72; On intel macOS machines a nightly release is never found

### LINKED ISSUE #72: On intel macOS machines a nightly release is never found with  v0.8.12
This line https://github.com/nim-lang/choosenim/blob/9b4797505dfa2367881a8e37ee81c4841cb86397/src/choosenimpkg/download.nim#L53C19-L53C24 makes intel macos always fail to find a nightly release. The following message is always displayed: `Warning Recent nightly release not found, installing latest devel commit.`.

Intel macos builds have `macosx_x64` in the failename, not `macosx_amd64` but the code is expecting the latter.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #72

### CODE REVIEW

File: src/choosenimpkg/download.nim [hunk 1]
```diff
@@ -50,7 +50,7 @@ proc getNightliesUrl(parsedContents: JsonNode, arch: int): (string, string) =
               if "arm64" in aname:
                 result = (url, tagName)
             else:
-              if "amd64" in aname:
+              if $hostCPU in aname:
```
Comment (ringabout) [inline src/choosenimpkg/download.nim:53]:
```suggestion
              if "x64" in aname:
```
